### ISSUE TITLE
Error in Exception and syntax problem in ikeclient.py

### ISSUE THREAD

**Issue by dxflatline** [SpiderLabs/ikeforce#2]
Hi very nice tool.
Spotted a problem while using AES with keyLen 256bit. It would stick to the default 128bit.

Traced the error at https://github.com/SpiderLabs/ikeforce/blob/master/ikeclient.py#L218-L221

You will need to correct "padding1+**encTypehashType**+**authtype**" to "padding1+**encType**+**hashType**+**authType**"

Now the exception does not makes sense at all since it was erroneously added due to this syntax error (in a hurry? :) )

Better to check if the keyLen is None or empty. Please feel free to commit the best option since you know the protocol lots better than me..

Thanks,

Dimitris Strevinas

**Comment by f0cker** [comment]
Thanks for pointing this out, I'll fix it up shortly :)
